const TOOTH_IDS = [
  "PERMANENT_UPPER_RIGHT_THIRD_MOLAR",
  "PERMANENT_UPPER_RIGHT_SECOND_MOLAR",
  "PERMANENT_UPPER_RIGHT_FIRST_MOLAR",
  "PERMANENT_UPPER_RIGHT_SECOND_PREMOLAR",
  "PERMANENT_UPPER_RIGHT_FIRST_PREMOLAR",
  "PERMANENT_UPPER_RIGHT_CANINE",
  "PERMANENT_UPPER_RIGHT_LATERAL_INCISOR",
  "PERMANENT_UPPER_RIGHT_CENTRAL_INCISOR",
  "PERMANENT_UPPER_LEFT_CENTRAL_INCISOR",
  "PERMANENT_UPPER_LEFT_LATERAL_INCISOR",
  "PERMANENT_UPPER_LEFT_CANINE",
  "PERMANENT_UPPER_LEFT_FIRST_PREMOLAR",
  "PERMANENT_UPPER_LEFT_SECOND_PREMOLAR",
  "PERMANENT_UPPER_LEFT_FIRST_MOLAR",
  "PERMANENT_UPPER_LEFT_SECOND_MOLAR",
  "PERMANENT_UPPER_LEFT_THIRD_MOLAR",
  "PERMANENT_LOWER_LEFT_THIRD_MOLAR",
  "PERMANENT_LOWER_LEFT_SECOND_MOLAR",
  "PERMANENT_LOWER_LEFT_FIRST_MOLAR",
  "PERMANENT_LOWER_LEFT_SECOND_PREMOLAR",
  "PERMANENT_LOWER_LEFT_FIRST_PREMOLAR",
  "PERMANENT_LOWER_LEFT_CANINE",
  "PERMANENT_LOWER_LEFT_LATERAL_INCISOR",
  "PERMANENT_LOWER_LEFT_CENTRAL_INCISOR",
  "PERMANENT_LOWER_RIGHT_CENTRAL_INCISOR",
  "PERMANENT_LOWER_RIGHT_LATERAL_INCISOR",
  "PERMANENT_LOWER_RIGHT_CANINE",
  "PERMANENT_LOWER_RIGHT_FIRST_PREMOLAR",
  "PERMANENT_LOWER_RIGHT_SECOND_PREMOLAR",
  "PERMANENT_LOWER_RIGHT_FIRST_MOLAR",
  "PERMANENT_LOWER_RIGHT_SECOND_MOLAR",
  "PERMANENT_LOWER_RIGHT_THIRD_MOLAR"
];

const VALID_TOOTH_IDS = new Set(TOOTH_IDS);

function isValidToothId(value) {
  return typeof value === "string" && VALID_TOOTH_IDS.has(value.trim());
}

module.exports = {
  TOOTH_IDS,
  VALID_TOOTH_IDS,
  isValidToothId
};
